# Pandas - wczytywanie danych - zadania

In [1]:
import pandas as pd

## Pandas Read CSV Dates

1. Użyj danych z sekcji "Input" (patrz poniżej)
1. Wczytaj dane z ``URL`` do ``df: pd.DataFrame``
1. Sparsuj daty w kolumnie "Mission Date"

Podpowiedź:
* ``parse_dates`` argument

In [7]:
URL = 'https://python.astrotech.io/_static/astro-dates.csv'
df = pd.read_csv(URL)

In [13]:
MONTHS = {
    'styczeń': 'January',
    'lipiec': 'July',
    'kwiecień': 'April',
    'grudzień': 'December',
}

df['Mission Date'].replace(MONTHS, regex=True, inplace=True)
df['Mission Date'] = pd.to_datetime(df['Mission Date'])

In [14]:
df

   id First Name   Last Name Mission Date
0   1        Jan  Twardowski   1988-01-05
1   2       Mark      Watney   1969-07-21
2   3       Ivan   Ivanovich   1961-04-12
3   4    Melissa       Lewis   1970-01-01
4   5       Alex       Vogel   1968-12-25

## Pandas Read CSV Replace

1. Użyj danych z sekcji "Input" (patrz poniżej)
1. Wczytaj dane z ``URL`` do ``DataFrame``
1. Użyj podanych w ``COLUMNS`` nazw kolumn
1. Wczytaj nazwy labeli z pierwszego wiersza
1. Podmień dane w kolumnie ``label`` na wartości wyciągnięte powyżej
1. Wypisz pierwsze 5 wierszy z ``df: pd.DataFrame``

Podpowiedź:
* ``pd.read_csv(url, nrows=0).columns``
* ``df['label'].replace({'from': 'to'}, inplace=True)``

In [21]:
URL = 'https://python.astrotech.io/_static/breast-cancer.csv'

COLUMNS = ['mean radius', 'mean texture', 'mean perimeter', 'mean area',
           'mean smoothness', 'mean compactness', 'mean concavity',
           'mean concave points', 'mean symmetry', 'mean fractal dimension',
           'radius error', 'texture error', 'perimeter error', 'area error',
           'smoothness error', 'compactness error', 'concavity error',
           'concave points error', 'symmetry error',
           'fractal dimension error', 'worst radius', 'worst texture',
           'worst perimeter', 'worst area', 'worst smoothness',
           'worst compactness', 'worst concavity', 'worst concave points',
           'worst symmetry', 'worst fractal dimension', 'label']

LABEL = pd.read_csv(URL, nrows=0).columns[2:]
LABEL = dict(enumerate(LABEL))

df = pd.read_csv(URL, names=COLUMNS, skiprows=1)
df['label'].replace(LABEL, inplace=True)
df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,label
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,malignant
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,malignant
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,malignant
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,malignant
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,malignant
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,malignant
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,malignant
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,malignant
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,malignant
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,benign

## Pandas Read JSON

1. Użyj danych z sekcji "Input" (patrz poniżej)
1. Za pomocą ``pd.read_json()`` wczytaj dane z ``URL``
1. Wypisz ``df: pd.DataFrame``

In [22]:
URL = 'https://python.astrotech.io/_static/iris.json'
pd.read_json(URL)

    sepalLength  sepalWidth  petalLength  petalWidth     species
0           5.1         3.5          1.4         0.2      setosa
1           4.9         3.0          1.4         0.2      setosa
2           4.7         3.2          1.3         0.2      setosa
3           4.6         3.1          1.5         0.2      setosa
4           5.0         3.6          1.4         0.2      setosa
5           5.4         3.9          1.7         0.4      setosa
6           4.6         3.4          1.4         0.3      setosa
7           5.0         3.4          1.5         0.2      setosa
8           4.4         2.9          1.4         0.2      setosa
9           4.9         3.1          1.5         0.1      setosa
10          7.0         3.2          4.7         1.4  versicolor
11          6.4         3.2          4.5         1.5  versicolor
12          6.9         3.1          4.9         1.5  versicolor
13          5.5         2.3          4.0         1.3  versicolor
14          6.5         2.8          4.6         1.5  versicolor
15          5.7         2.8          4.5         1.3  versicolor
16          6.3         3.3          4.7         1.6  versicolor
17          4.9         2.4          3.3         1.0  versicolor
18          6.6         2.9          4.6         1.3  versicolor
19          5.2         2.7          3.9         1.4  versicolor
20          6.3         3.3          6.0         2.5   virginica
21          5.8         2.7          5.1         1.9   virginica
22          7.1         3.0          5.9         2.1   virginica
23          6.3         2.9          5.6         1.8   virginica
24          6.5         3.0          5.8         2.2   virginica
25          7.6         3.0          6.6         2.1   virginica
26          4.9         2.5          4.5         1.7   virginica
27          7.3         2.9          6.3         1.8   virginica
28          6.7         2.5          5.8         1.8   virginica
29          7.2         3.6          6.1         2.5   virginica

## Pandas Read HTML

1. Użyj danych z sekcji "Input" (patrz poniżej)
1. Za pomocą ``pd.read_html()`` wczytaj dane z ``URL``
1. Wypisz ``df: pd.DataFrame`` z aktywnymi astronautami Europejskiej Agencji Kosmicznej

Podpowiedź:

- Może wymagać instalacji ``lxml`` oraz ``html5lib``: ``pip install --upgrade lxml html5lib``
- ``pd.read_html()`` zwraca listę tabel na stronie, poszukaj która ma odpowiednie dane

In [23]:
URL = 'https://python.astrotech.io/_static/european-astronaut-corps.html'

In [28]:
tables = pd.read_html(URL)

In [42]:
acive = tables[3]
acive['Time in space'] = acive['Time in space'].map(pd.Timedelta)
acive['Time in space'].sum()

Timedelta('1321 days 05:48:00')

In [43]:
former = tables[4]
former['Time in space'] = former['Time in space'].map(pd.Timedelta)
former['Time in space'].sum()

Timedelta('1715 days 00:13:00')

In [44]:
pd.Timedelta('1715 days 00:13:00') + pd.Timedelta('1321 days 05:48:00')

Timedelta('3036 days 06:01:00')

In [45]:
duration = pd.Timedelta('3036 days 06:01:00')

In [47]:
duration.days / 365

8.317808219178081