# Pandas - DataFrame - wyszukiwanie - zadania

In [1]:
import pandas as pd

## DataFrame Sample

1. Użyj danych z sekcji "Input" (patrz poniżej)
1. Wczytaj dane z ``DATA`` jako ``astronauts: pd.DataFrame``
1. W danych kolumna "Order":

    - określa kolejność astronauty/kosmonauty w kosmosie
    - Czasami kilka osób leciało tym samym statkiem i ich numery powinny być takie same, a w danych jest ``NaN``.
    - Wypełnij brakujące indeksy stosując ``df.ffill()``

1. Ustaw wszystkie wiersze w losowej kolejności
1. Zresetuj index nie pozostawiając kopii zapasowej starego
1. Wypisz

    * Pierwsze trzy wiersze
    * Ostatnie 10% wierszy

In [18]:
DATA = 'https://python.astrotech.io/_static/astro-flights.csv'

astronauts = pd.read_csv(DATA)
astronauts['Order'] = astronauts['Order'].ffill().map(int)
astronauts = astronauts.sample(frac=1.0).reset_index(drop=True)

astronauts.head(n=3)

In [26]:
idx = int(len(astronauts) * 0.1)
astronauts[-idx:]

     Order                         Astronaut         Date         Mission
482    171                   Sherwood Spring   1985-11-27            61-B
483    395                 Mark Shuttleworth   2002-04-25     Soyuz TM-34
484    223                  Donald McMonagle   1991-04-28          STS-39
485    104               Daniel Brandenstein   1983-08-30           STS-8
486    276                  Vasili Tsibliyev   1993-07-01     Soyuz TM-17
487    302                   William Gregory   1995-03-02          STS-67
488     92                    William Lenoir   1982-11-11           STS-5
489     32                   Viktor Patsayev   1971-06-06        Soyuz 11
490    104                      Dale Gardner   1983-08-30           STS-8
491    338                    Carlos Noriega   1997-05-15          STS-84
492    267                  Kenneth Cockrell   1993-04-08          STS-56
493     66              Vladimir Dzhanibekov   1978-01-10        Soyuz 27
494     26                        Fred Haise   1970-04-11       Apollo 13
495      1                      Yuri Gagarin   1961-04-12          Vostok
496     63                     Valeri Ryumin   1977-10-09        Soyuz 25
497    238                        James Voss   1991-11-25          STS-44
498    287                      Thomas Jones   1994-04-09          STS-59
499     99                        Sally Ride   1983-06-18           STS-7
500    392                         Lee Morin   2002-04-08         STS-110
501    444                  Douglas Wheelock   2007-10-23         STS-120
502     99                    Norman Thagard   1983-06-18           STS-7
503    124                     Steven Hawley   1984-08-30            41-D
504    429                 Joan Higginbotham   2006-12-10         STS-116
505     87                 Anatoli Berezovoi   1982-05-13       Soyuz T-5
506    434                   Charles Simonyi   2007-04-07    Soyuz TMA-10
507    491                       Terry Virts   2010-02-08         STS-130
508    259                      Mamoru Mohri   1992-09-12          STS-47
509     51                    Yuri Artyukhin   1974-07-03        Soyuz 14
510    108                     Robert Parker   1983-11-28           STS-9
511    345                   Leonid Kadenyuk   1997-11-19          STS-87
512    429                Christer Fuglesang   2006-12-10         STS-116
513    216                   Samuel Durrance   1990-12-02          STS-35
514    264                  Michael Clifford   1992-12-02          STS-53
515    323                    Scott Horowitz   1996-02-22          STS-75
516    423                        Lisa Nowak   2006-07-04         STS-121
517    192                      James Bagian   1989-03-13          STS-29
518    462                      Zhai Zhigang   2008-09-25      ShenZhou 7
519    185   Aleksandr Panayotov Aleksandrov   1988-06-07      Soyuz TM-5
520    388                        Mark Kelly   2001-12-05         STS-108
521    361                      Yuri Baturin   1998-08-13     Soyuz TM-28
522    288                  Talgat Musabayev   1994-07-01     Soyuz TM-19
523    387                Konstantin Kozeyev   2001-10-21     Soyuz TM-33
524    230                   Francis Gaffney   1991-06-05          STS-40
525    397                     Paul Lockhart   2002-06-05         STS-111
526     54                    Georgi Grechko   1975-01-10        Soyuz 17
527    256                  Claude Nicollier   1992-07-31          STS-46
528    349                 Saliszan Sharipov   1998-01-23          STS-89
529    498                   Oleg Skripochka   2010-10-07   Soyuz TMA-01M
530    203                        George Low   1990-01-09          STS-32
531    116                 Vladimir Solovyov   1984-02-08      Soyuz T-10
532    187                     Abdul Mohmand   1988-08-29      Soyuz TM-6
533    500                  Andrei Borisenko   2011-04-04    Soyuz TMA-21
534    377                     Pamela Melroy   2000-10-11          STS-92

## DataFrame Select

1. Użyj danych z sekcji "Input" (patrz poniżej)
1. Wczytaj dane z ``DATA`` jako ``iris: pd.DataFrame``
1. Przefiltruj ``inplace`` kolumnę 'Petal length' i pozostaw wartości powyżej 2.0
1. Wyświetl 5 pierwszych wierszy

In [27]:
DATA = 'https://python.astrotech.io/_static/iris-clean.csv'

iris = pd.read_csv(DATA)

In [32]:
iris[iris['petal_length'] > 2.0].head(5)

   sepal_length  sepal_width  petal_length  petal_width     species
1           5.9          3.0           5.1          1.8   virginica
2           6.0          3.4           4.5          1.6  versicolor
3           7.3          2.9           6.3          1.8   virginica
4           5.6          2.5           3.9          1.1  versicolor
6           5.5          2.6           4.4          1.2  versicolor